// examples/sendPhoto/for-react.tsx
import { useState } from 'react'
import { TelegramBot } from 'tele-sdk-js' // Replace with actual SDK import

const bot = new TelegramBot('YOUR_BOT_TOKEN')

function SendPhotoComponent() {
	const [chatId, setChatId] = useState('')
	const [photoUrl, setPhotoUrl] = useState('')
	const [message, setMessage] = useState('')

	const sendPhoto = async () => {
		try {
			const response = await bot.sendPhoto({
				chat_id: chatId,
				photo: photoUrl,
				caption: message,
			})
			console.log('Photo sent:', response)
		} catch (error) {
			console.error('Error:', error)
		}
	}

	return (
		<div>
			<input
				type='text'
				placeholder='Chat ID'
				value={chatId}
				onChange={e => setChatId(e.target.value)}
			/>
			<input
				type='text'
				placeholder='Photo URL'
				value={photoUrl}
				onChange={e => setPhotoUrl(e.target.value)}
			/>
			<input
				type='text'
				placeholder='Caption'
				value={message}
				onChange={e => setMessage(e.target.value)}
			/>
			<button onClick={sendPhoto}>Send Photo</button>
		</div>
	)
}

export default SendPhotoComponent

// examples/sendPhoto/for-vue.vue
<template>
  <div>
    <input v-model="chatId" placeholder="Chat ID" />
    <input v-model="photoUrl" placeholder="Photo URL" />
    <input v-model="caption" placeholder="Caption" />
    <button @click="sendPhoto">Send Photo</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import {TelegramBot} from 'tele-sdk-js'; // Replace with actual SDK import

const bot = new TelegramBot('YOUR_BOT_TOKEN');

const chatId = ref('');
const photoUrl = ref('');
const caption = ref('');

const sendPhoto = async () => {
  try {
    const response = await bot.sendPhoto({
      chat_id: chatId.value,
      photo: photoUrl.value,
      caption: caption.value,
    });
    console.log('Photo sent:', response);
  } catch (error) {
    console.error('Error sending photo:', error);
  }
};
</script>
